//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package ch.hslu.edu.enapp.webshop.webservices.enappdaemon;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "Item_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", wsdlLocation = "/META-INF/wsdl/ItemService.wsdl" )
public class ItemService
    extends Service
{

    private final static URL ITEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMSERVICE_EXCEPTION;
    private final static QName ITEMSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Item_Service");

    static {
        ITEMSERVICE_WSDL_LOCATION = ch.hslu.edu.enapp.webshop.webservices.enappdaemon.ItemService.class.getResource("/META-INF/wsdl/ItemService.wsdl");
        WebServiceException e = null;
        if (ITEMSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/ItemService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ITEMSERVICE_EXCEPTION = e;
    }

    public ItemService() {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME);
    }

    public ItemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation) {
        super(wsdlLocation, ITEMSERVICE_QNAME);
    }

    public ItemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemPort
     */
    @WebEndpoint(name = "Item_Port")
    public ItemPort getItemPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item", "Item_Port"), ItemPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemPort
     */
    @WebEndpoint(name = "Item_Port")
    public ItemPort getItemPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item", "Item_Port"), ItemPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMSERVICE_EXCEPTION!= null) {
            throw ITEMSERVICE_EXCEPTION;
        }
        return ITEMSERVICE_WSDL_LOCATION;
    }

}
