//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package ch.hslu.edu.enapp.webshop.webservices.enappdaemon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.hslu.edu.enapp.webshop.webservices.enappdaemon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Delete_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Delete");
    private final static QName _UpdateMultipleResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "UpdateMultiple_Result");
    private final static QName _IsUpdatedResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "IsUpdated_Result");
    private final static QName _IsUpdated_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "IsUpdated");
    private final static QName _ReadResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Read_Result");
    private final static QName _UpdateResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Update_Result");
    private final static QName _CreateMultiple_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "CreateMultiple");
    private final static QName _ReadMultipleResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "ReadMultiple_Result");
    private final static QName _ReadMultiple_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "ReadMultiple");
    private final static QName _Update_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Update");
    private final static QName _CreateResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Create_Result");
    private final static QName _Read_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Read");
    private final static QName _DeleteResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Delete_Result");
    private final static QName _UpdateMultiple_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "UpdateMultiple");
    private final static QName _CreateMultipleResult_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "CreateMultiple_Result");
    private final static QName _Create_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item", "Create");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.hslu.edu.enapp.webshop.webservices.enappdaemon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteResult }
     * 
     */
    public DeleteResult createDeleteResult() {
        return new DeleteResult();
    }

    /**
     * Create an instance of {@link UpdateMultipleResult }
     * 
     */
    public UpdateMultipleResult createUpdateMultipleResult() {
        return new UpdateMultipleResult();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link CreateResult }
     * 
     */
    public CreateResult createCreateResult() {
        return new CreateResult();
    }

    /**
     * Create an instance of {@link UpdateResult }
     * 
     */
    public UpdateResult createUpdateResult() {
        return new UpdateResult();
    }

    /**
     * Create an instance of {@link IsUpdated }
     * 
     */
    public IsUpdated createIsUpdated() {
        return new IsUpdated();
    }

    /**
     * Create an instance of {@link IsUpdatedResult }
     * 
     */
    public IsUpdatedResult createIsUpdatedResult() {
        return new IsUpdatedResult();
    }

    /**
     * Create an instance of {@link UpdateMultiple }
     * 
     */
    public UpdateMultiple createUpdateMultiple() {
        return new UpdateMultiple();
    }

    /**
     * Create an instance of {@link ReadMultipleResult }
     * 
     */
    public ReadMultipleResult createReadMultipleResult() {
        return new ReadMultipleResult();
    }

    /**
     * Create an instance of {@link ReadResult }
     * 
     */
    public ReadResult createReadResult() {
        return new ReadResult();
    }

    /**
     * Create an instance of {@link Create }
     * 
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link Read }
     * 
     */
    public Read createRead() {
        return new Read();
    }

    /**
     * Create an instance of {@link CreateMultiple }
     * 
     */
    public CreateMultiple createCreateMultiple() {
        return new CreateMultiple();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link CreateMultipleResult }
     * 
     */
    public CreateMultipleResult createCreateMultipleResult() {
        return new CreateMultipleResult();
    }

    /**
     * Create an instance of {@link ReadMultiple }
     * 
     */
    public ReadMultiple createReadMultiple() {
        return new ReadMultiple();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ItemFilter }
     * 
     */
    public ItemFilter createItemFilter() {
        return new ItemFilter();
    }

    /**
     * Create an instance of {@link ItemList }
     * 
     */
    public ItemList createItemList() {
        return new ItemList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Delete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Delete")
    public JAXBElement<Delete> createDelete(Delete value) {
        return new JAXBElement<Delete>(_Delete_QNAME, Delete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMultipleResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "UpdateMultiple_Result")
    public JAXBElement<UpdateMultipleResult> createUpdateMultipleResult(UpdateMultipleResult value) {
        return new JAXBElement<UpdateMultipleResult>(_UpdateMultipleResult_QNAME, UpdateMultipleResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsUpdatedResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "IsUpdated_Result")
    public JAXBElement<IsUpdatedResult> createIsUpdatedResult(IsUpdatedResult value) {
        return new JAXBElement<IsUpdatedResult>(_IsUpdatedResult_QNAME, IsUpdatedResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsUpdated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "IsUpdated")
    public JAXBElement<IsUpdated> createIsUpdated(IsUpdated value) {
        return new JAXBElement<IsUpdated>(_IsUpdated_QNAME, IsUpdated.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Read_Result")
    public JAXBElement<ReadResult> createReadResult(ReadResult value) {
        return new JAXBElement<ReadResult>(_ReadResult_QNAME, ReadResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Update_Result")
    public JAXBElement<UpdateResult> createUpdateResult(UpdateResult value) {
        return new JAXBElement<UpdateResult>(_UpdateResult_QNAME, UpdateResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMultiple }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "CreateMultiple")
    public JAXBElement<CreateMultiple> createCreateMultiple(CreateMultiple value) {
        return new JAXBElement<CreateMultiple>(_CreateMultiple_QNAME, CreateMultiple.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadMultipleResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "ReadMultiple_Result")
    public JAXBElement<ReadMultipleResult> createReadMultipleResult(ReadMultipleResult value) {
        return new JAXBElement<ReadMultipleResult>(_ReadMultipleResult_QNAME, ReadMultipleResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadMultiple }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "ReadMultiple")
    public JAXBElement<ReadMultiple> createReadMultiple(ReadMultiple value) {
        return new JAXBElement<ReadMultiple>(_ReadMultiple_QNAME, ReadMultiple.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Update }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Update")
    public JAXBElement<Update> createUpdate(Update value) {
        return new JAXBElement<Update>(_Update_QNAME, Update.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Create_Result")
    public JAXBElement<CreateResult> createCreateResult(CreateResult value) {
        return new JAXBElement<CreateResult>(_CreateResult_QNAME, CreateResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Read }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Read")
    public JAXBElement<Read> createRead(Read value) {
        return new JAXBElement<Read>(_Read_QNAME, Read.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Delete_Result")
    public JAXBElement<DeleteResult> createDeleteResult(DeleteResult value) {
        return new JAXBElement<DeleteResult>(_DeleteResult_QNAME, DeleteResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMultiple }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "UpdateMultiple")
    public JAXBElement<UpdateMultiple> createUpdateMultiple(UpdateMultiple value) {
        return new JAXBElement<UpdateMultiple>(_UpdateMultiple_QNAME, UpdateMultiple.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMultipleResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "CreateMultiple_Result")
    public JAXBElement<CreateMultipleResult> createCreateMultipleResult(CreateMultipleResult value) {
        return new JAXBElement<CreateMultipleResult>(_CreateMultipleResult_QNAME, CreateMultipleResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Create }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:microsoft-dynamics-schemas/page/item", name = "Create")
    public JAXBElement<Create> createCreate(Create value) {
        return new JAXBElement<Create>(_Create_QNAME, Create.class, null, value);
    }

}
